name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_NAME: vicare-exporter

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
        --tag ghcr.io/sebbegg/${IMAGE_NAME}:${{ github.run_id }} \
        --tag ghcr.io/sebbegg/${IMAGE_NAME}:latest
        
    - name: Push docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push -a ghcr.io/sebbegg/${IMAGE_NAME}
    
